### ISSUE TITLE
Adding a peer doesn't work

### ISSUE THREAD

**Issue by MatthewCochrane** [lmangani/gun-scape#4]
Tried adding a peer using the following code in the console at 

    g.opt({peers: ['https://mytesturl.com/gun']})

But nothing happened.  Not sure if this should work, but this would certainly be a more useful tool if you could use it to visualise an existing database rather than having to input all the nodes manually.

**Comment by lmangani** [comment]
It's well possible to achieve your goal using the same code and libraries, but that's not the purpose of the public demo which is simply to teach GUN syntax and explain Graph relations visually. Thanks!

**Comment by MatthewCochrane** [comment]
@lmangani Great.  Thanks for the feedback.

**Comment by lmangani** [comment]
FYI I'm doing pretty much what you described in Elasticsearch using `gun-elastic` and our own plugin to display, search and filter nodes and relations. The same is possible with other storage adaptors, too.
